export const PREDICT_MOVE_REQUEST = 'PREDICT_MOVE_REQUEST';
export const PREDICT_MOVE_SUCCESS = 'PREDICT_MOVE_SUCCESS';
export const PREDICT_MOVE_FAILURE = 'PREDICT_MOVE_FAILURE';

export const PLAYER_MOVE = 'PLAYER_MOVE';
export const START_GAME = 'START_GAME';

export const STOP_GAME_X_WON = 'STOP_GAME_X_WON';
export const STOP_GAME_O_WON = 'STOP_GAME_O_WON';
export const STOP_GAME_DRAW = 'STOP_GAME_DRAW';

export const GET_ACCURACY_REQUEST = 'GET_ACCURACY_REQUEST';
export const GET_ACCURACY_SUCCESS = 'GET_ACCURACY_SUCCESS';
export const GET_ACCURACY_FAILURE = 'GET_ACCURACY_FAILURE';

export const TRAIN_NN_REQUEST = 'TRAIN_NN_REQUEST';
export const TRAIN_NN_SUCCESS = 'TRAIN_NN_SUCCESS';
export const TRAIN_NN_FAILURE = 'TRAIN_NN_FAILURE';
