export const PREDICT_MOVE_REQUEST_V1 = 'PREDICT_MOVE_REQUEST_V1';
export const PREDICT_MOVE_SUCCESS_V1 = 'PREDICT_MOVE_SUCCESS_V1';
export const PREDICT_MOVE_FAILURE_V1 = 'PREDICT_MOVE_FAILURE_V1';

export const PLAYER_MOVE_V1 = 'PLAYER_MOVE_V1';
export const START_GAME_V1 = 'START_GAME_V1';

export const STOP_GAME_X_WON_V1 = 'STOP_GAME_X_WON_V1';
export const STOP_GAME_O_WON_V1 = 'STOP_GAME_O_WON_V1';
export const STOP_GAME_DRAW_V1 = 'STOP_GAME_DRAW_V1';

export const GET_ACCURACY_REQUEST_V1 = 'GET_ACCURACY_REQUEST_V1';
export const GET_ACCURACY_SUCCESS_V1 = 'GET_ACCURACY_SUCCESS_V1';
export const GET_ACCURACY_FAILURE_V1 = 'GET_ACCURACY_FAILURE_V1';

export const TRAIN_NN_REQUEST_V1 = 'TRAIN_NN_REQUEST_V1';
export const TRAIN_NN_SUCCESS_V1 = 'TRAIN_NN_SUCCESS_V1';
export const TRAIN_NN_FAILURE_V1 = 'TRAIN_NN_FAILURE_V1';

export const PREDICT_MOVE_REQUEST_V2 = 'PREDICT_MOVE_REQUEST_V2';
export const PREDICT_MOVE_SUCCESS_V2 = 'PREDICT_MOVE_SUCCESS_V2';
export const PREDICT_MOVE_FAILURE_V2 = 'PREDICT_MOVE_FAILURE_V2';

export const PLAYER_MOVE_V2 = 'PLAYER_MOVE_V2';
export const START_GAME_V2 = 'START_GAME_V2';

export const STOP_GAME_X_WON_V2 = 'STOP_GAME_X_WON_V2';
export const STOP_GAME_O_WON_V2 = 'STOP_GAME_O_WON_V2';
export const STOP_GAME_DRAW_V2 = 'STOP_GAME_DRAW_V2';

export const GET_ACCURACY_REQUEST_V2 = 'GET_ACCURACY_REQUEST_V2';
export const GET_ACCURACY_SUCCESS_V2 = 'GET_ACCURACY_SUCCESS_V2';
export const GET_ACCURACY_FAILURE_V2 = 'GET_ACCURACY_FAILURE_V2';

export const TRAIN_BY_MOVES_REQUEST_V2 = 'TRAIN_BY_MOVES_REQUEST_V2';
export const TRAIN_BY_MOVES_SUCCESS_V2 = 'TRAIN_BY_MOVES_SUCCESS_V2';
export const TRAIN_BY_MOVES_FAILURE_V2 = 'TRAIN_BY_MOVES_FAILURE_V2';

export const TRAIN_NN_REQUEST_V2 = 'TRAIN_NN_REQUEST_V2';
export const TRAIN_NN_SUCCESS_V2 = 'TRAIN_NN_SUCCESS_V2';
export const TRAIN_NN_FAILURE_V2 = 'TRAIN_NN_FAILURE_V2';

export const PREDICT_MOVE_REQUEST_V3 = 'PREDICT_MOVE_REQUEST_V3';
export const PREDICT_MOVE_SUCCESS_V3 = 'PREDICT_MOVE_SUCCESS_V3';
export const PREDICT_MOVE_FAILURE_V3 = 'PREDICT_MOVE_FAILURE_V3';

export const UNBEAT_MOVE_REQUEST_V3 = 'UNBEAT_MOVE_REQUEST_V3';
export const UNBEAT_MOVE_SUCCESS_V3 = 'UNBEAT_MOVE_SUCCESS_V3';
export const UNBEAT_MOVE_FAILURE_V3 = 'UNBEAT_MOVE_FAILURE_V3';

export const START_GAME_V3 = 'START_GAME_V3';

export const STOP_GAME_X_WON_V3 = 'STOP_GAME_X_WON_V3';
export const STOP_GAME_O_WON_V3 = 'STOP_GAME_O_WON_V3';
export const STOP_GAME_DRAW_V3 = 'STOP_GAME_DRAW_V3';

export const TRAIN_NN_REQUEST_V3 = 'TRAIN_NN_REQUEST_V3';
export const TRAIN_NN_SUCCESS_V3 = 'TRAIN_NN_SUCCESS_V3';
export const TRAIN_NN_FAILURE_V3 = 'TRAIN_NN_FAILURE_V3';

export const ADD_TRAINING_DATA_REQUEST_V3 = 'ADD_TRAINING_DATA_REQUEST_V3';
export const ADD_TRAINING_DATA_SUCCESS_V3 = 'ADD_TRAINING_DATA_SUCCESS_V3';
export const ADD_TRAINING_DATA_FAILURE_V3 = 'ADD_TRAINING_DATA_FAILURE_V3';
